In [46]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import tensorflow
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense 

In [47]:
traindf = pd.read_csv('/content/Admission_Predict.csv')

In [48]:
traindf.head()

Serial No.  GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  \
0           1        337          118                  4  4.5   4.5  9.65   
1           2        324          107                  4  4.0   4.5  8.87   
2           3        316          104                  3  3.0   3.5  8.00   
3           4        322          110                  3  3.5   2.5  8.67   
4           5        314          103                  2  2.0   3.0  8.21   

   Research  Chance of Admit   
0         1              0.92  
1         1              0.76  
2         1              0.72  
3         1              0.80  
4         0              0.65

In [49]:
traindf.drop(columns=['Serial No.'], inplace=True)

In [50]:
traindf.head()

GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  Research  \
0        337          118                  4  4.5   4.5  9.65         1   
1        324          107                  4  4.0   4.5  8.87         1   
2        316          104                  3  3.0   3.5  8.00         1   
3        322          110                  3  3.5   2.5  8.67         1   
4        314          103                  2  2.0   3.0  8.21         0   

   Chance of Admit   
0              0.92  
1              0.76  
2              0.72  
3              0.80  
4              0.65

In [51]:
y = traindf.iloc[:, -1]

In [52]:
X = traindf.iloc[:, :-1]

In [53]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=24)


In [54]:
X_train.shape

(320, 7)

In [55]:
X_test.shape

(80, 7)

In [56]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()


In [57]:
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [58]:
X_train_scaled

array([[0.52      , 0.64285714, 0.5       , ..., 0.875     , 0.63461538,
        1.        ],
       [0.58      , 0.5       , 0.5       , ..., 0.5       , 0.38461538,
        1.        ],
       [0.7       , 0.67857143, 0.5       , ..., 0.625     , 0.60897436,
        0.        ],
       ...,
       [0.3       , 0.39285714, 0.25      , ..., 0.625     , 0.42628205,
        0.        ],
       [0.64      , 0.78571429, 1.        , ..., 0.75      , 0.68589744,
        1.        ],
       [0.34      , 0.46428571, 0.25      , ..., 0.625     , 0.41666667,
        0.        ]])

In [59]:
X_test_scaled

array([[0.4       , 0.5       , 0.75      , 0.875     , 0.875     ,
        0.71794872, 1.        ],
       [0.54      , 0.53571429, 0.5       , 0.625     , 0.5       ,
        0.6025641 , 1.        ],
       [0.6       , 0.42857143, 0.5       , 0.625     , 0.875     ,
        0.49358974, 1.        ],
       [1.        , 1.        , 0.75      , 1.        , 1.        ,
        0.86538462, 1.        ],
       [0.3       , 0.46428571, 0.25      , 0.5       , 0.75      ,
        0.42628205, 0.        ],
       [0.22      , 0.42857143, 0.25      , 0.625     , 0.625     ,
        0.34935897, 1.        ],
       [0.74      , 0.71428571, 0.5       , 0.5       , 0.5       ,
        0.61538462, 1.        ],
       [0.34      , 0.35714286, 0.5       , 0.5       , 0.5       ,
        0.47115385, 0.        ],
       [0.68      , 0.71428571, 0.75      , 0.75      , 0.625     ,
        0.63141026, 1.        ],
       [0.62      , 0.64285714, 0.5       , 0.625     , 1.        ,
        0.65705128, 1. 

In [60]:
model = Sequential()

model.add(Dense(7, activation='relu', input_dim=7))
model.add(Dense(1, activation='linear'))


In [61]:
model.compile(loss='mean_squared_error',  optimizer='Adam', metrics=['accuracy'])

In [62]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_2 (Dense)             (None, 7)                 56        
                                                                 
 dense_3 (Dense)             (None, 1)                 8         
                                                                 
Total params: 64
Trainable params: 64
Non-trainable params: 0
_________________________________________________________________


In [63]:
model.fit(X_train_scaled, y_train, epochs=10, validation_split=0.2)

Epoch 1/10
8/8 [==============================] - 1s 26ms/step - loss: 0.4614 - accuracy: 0.0000e+00 - val_loss: 0.3443 - val_accuracy: 0.0000e+00
Epoch 2/10
8/8 [==============================] - 0s 8ms/step - loss: 0.3539 - accuracy: 0.0000e+00 - val_loss: 0.2601 - val_accuracy: 0.0000e+00
Epoch 3/10
8/8 [==============================] - 0s 6ms/step - loss: 0.2666 - accuracy: 0.0000e+00 - val_loss: 0.1894 - val_accuracy: 0.0000e+00
Epoch 4/10
8/8 [==============================] - 0s 5ms/step - loss: 0.1920 - accuracy: 0.0000e+00 - val_loss: 0.1341 - val_accuracy: 0.0000e+00
Epoch 5/10
8/8 [==============================] - 0s 6ms/step - loss: 0.1353 - accuracy: 0.0000e+00 - val_loss: 0.0926 - val_accuracy: 0.0000e+00
Epoch 6/10
8/8 [==============================] - 0s 5ms/step - loss: 0.0924 - accuracy: 0.0000e+00 - val_loss: 0.0642 - val_accuracy: 0.0000e+00
Epoch 7/10
8/8 [==============================] - 0s 5ms/step - loss: 0.0637 - accuracy: 0.0000e+00 - val_loss: 0.0456 - va

In [64]:
y_pred = model.predict(X_test_scaled)

In [65]:
y_pred

array([[0.5666926 ],
       [0.50631803],
       [0.7077995 ],
       [0.9994323 ],
       [0.6737389 ],
       [0.21395963],
       [0.66115123],
       [0.65639526],
       [0.6147351 ],
       [0.8000721 ],
       [0.6933013 ],
       [0.80648106],
       [0.66987896],
       [0.72458845],
       [0.86299706],
       [0.6343575 ],
       [0.734141  ],
       [0.45388123],
       [0.7635549 ],
       [0.41794917],
       [0.60935146],
       [0.5608193 ],
       [0.5316023 ],
       [0.5292869 ],
       [0.6052501 ],
       [0.76812667],
       [0.65095425],
       [0.34416962],
       [0.75809   ],
       [0.5648334 ],
       [0.9157242 ],
       [1.0140761 ],
       [0.9754699 ],
       [0.42204702],
       [0.91180605],
       [0.8007466 ],
       [0.5890344 ],
       [0.9551244 ],
       [0.42919973],
       [0.743306  ],
       [0.7629407 ],
       [0.6244022 ],
       [0.8102461 ],
       [0.5032347 ],
       [0.76256645],
       [0.76675385],
       [0.71700585],
       [0.797

In [67]:
from sklearn.metrics import r2_score

r2_score(y_pred, y_test)

0.23613422840410558