In [73]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import tensorflow
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense 

In [74]:
traindf = pd.read_csv('/content/Admission_Predict.csv')

In [75]:
traindf.head()

Serial No.  GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  \
0           1        337          118                  4  4.5   4.5  9.65   
1           2        324          107                  4  4.0   4.5  8.87   
2           3        316          104                  3  3.0   3.5  8.00   
3           4        322          110                  3  3.5   2.5  8.67   
4           5        314          103                  2  2.0   3.0  8.21   

   Research  Chance of Admit   
0         1              0.92  
1         1              0.76  
2         1              0.72  
3         1              0.80  
4         0              0.65

In [76]:
traindf.drop(columns=['Serial No.'], inplace=True)

In [77]:
traindf.head()

GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  Research  \
0        337          118                  4  4.5   4.5  9.65         1   
1        324          107                  4  4.0   4.5  8.87         1   
2        316          104                  3  3.0   3.5  8.00         1   
3        322          110                  3  3.5   2.5  8.67         1   
4        314          103                  2  2.0   3.0  8.21         0   

   Chance of Admit   
0              0.92  
1              0.76  
2              0.72  
3              0.80  
4              0.65

In [78]:
y = traindf.iloc[:, -1]

In [79]:
X = traindf.iloc[:, :-1]

In [80]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=24)


In [81]:
X_train.shape

(320, 7)

In [82]:
X_test.shape

(80, 7)

In [83]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()


In [84]:
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [85]:
X_train_scaled

array([[0.52      , 0.64285714, 0.5       , ..., 0.875     , 0.63461538,
        1.        ],
       [0.58      , 0.5       , 0.5       , ..., 0.5       , 0.38461538,
        1.        ],
       [0.7       , 0.67857143, 0.5       , ..., 0.625     , 0.60897436,
        0.        ],
       ...,
       [0.3       , 0.39285714, 0.25      , ..., 0.625     , 0.42628205,
        0.        ],
       [0.64      , 0.78571429, 1.        , ..., 0.75      , 0.68589744,
        1.        ],
       [0.34      , 0.46428571, 0.25      , ..., 0.625     , 0.41666667,
        0.        ]])

In [86]:
X_test_scaled

array([[0.4       , 0.5       , 0.75      , 0.875     , 0.875     ,
        0.71794872, 1.        ],
       [0.54      , 0.53571429, 0.5       , 0.625     , 0.5       ,
        0.6025641 , 1.        ],
       [0.6       , 0.42857143, 0.5       , 0.625     , 0.875     ,
        0.49358974, 1.        ],
       [1.        , 1.        , 0.75      , 1.        , 1.        ,
        0.86538462, 1.        ],
       [0.3       , 0.46428571, 0.25      , 0.5       , 0.75      ,
        0.42628205, 0.        ],
       [0.22      , 0.42857143, 0.25      , 0.625     , 0.625     ,
        0.34935897, 1.        ],
       [0.74      , 0.71428571, 0.5       , 0.5       , 0.5       ,
        0.61538462, 1.        ],
       [0.34      , 0.35714286, 0.5       , 0.5       , 0.5       ,
        0.47115385, 0.        ],
       [0.68      , 0.71428571, 0.75      , 0.75      , 0.625     ,
        0.63141026, 1.        ],
       [0.62      , 0.64285714, 0.5       , 0.625     , 1.        ,
        0.65705128, 1. 

In [105]:
model = Sequential()

model.add(Dense(7, activation='relu', input_dim=7))
model.add(Dense(7, activation='relu'))
model.add(Dense(3, activation='relu'))
model.add(Dense(1, activation='linear'))


In [106]:
model.compile(loss='mean_squared_error',  optimizer='Adam')

In [107]:
model.summary()

Model: "sequential_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_13 (Dense)            (None, 7)                 56        
                                                                 
 dense_14 (Dense)            (None, 7)                 56        
                                                                 
 dense_15 (Dense)            (None, 3)                 24        
                                                                 
 dense_16 (Dense)            (None, 1)                 4         
                                                                 
Total params: 140
Trainable params: 140
Non-trainable params: 0
_________________________________________________________________


In [108]:
model.fit(X_train_scaled, y_train, epochs=100)

Epoch 1/100
10/10 [==============================] - 0s 2ms/step - loss: 0.5481
Epoch 2/100
10/10 [==============================] - 0s 2ms/step - loss: 0.5081
Epoch 3/100
10/10 [==============================] - 0s 2ms/step - loss: 0.4795
Epoch 4/100
10/10 [==============================] - 0s 2ms/step - loss: 0.4546
Epoch 5/100
10/10 [==============================] - 0s 2ms/step - loss: 0.4308
Epoch 6/100
10/10 [==============================] - 0s 3ms/step - loss: 0.4067
Epoch 7/100
10/10 [==============================] - 0s 2ms/step - loss: 0.3814
Epoch 8/100
10/10 [==============================] - 0s 3ms/step - loss: 0.3558
Epoch 9/100
10/10 [==============================] - 0s 2ms/step - loss: 0.3288
Epoch 10/100
10/10 [==============================] - 0s 3ms/step - loss: 0.3003
Epoch 11/100
10/10 [==============================] - 0s 2ms/step - loss: 0.2703
Epoch 12/100
10/10 [==============================] - 0s 2ms/step - loss: 0.2375
Epoch 13/100
10/10 [=================

In [109]:
y_pred = model.predict(X_test_scaled)

In [110]:
y_pred

array([[0.79882514],
       [0.7318748 ],
       [0.6996366 ],
       [0.9483946 ],
       [0.64021635],
       [0.6565144 ],
       [0.7638491 ],
       [0.62606704],
       [0.8082748 ],
       [0.7879212 ],
       [0.56581026],
       [0.69572544],
       [0.6905813 ],
       [0.68842226],
       [0.93548906],
       [0.7204368 ],
       [0.63963246],
       [0.6126847 ],
       [0.8912803 ],
       [0.65028393],
       [0.7214648 ],
       [0.6315074 ],
       [0.54889405],
       [0.5197333 ],
       [0.6511432 ],
       [0.8840622 ],
       [0.7007352 ],
       [0.5050366 ],
       [0.6645817 ],
       [0.48579162],
       [0.8651356 ],
       [0.95569086],
       [0.92661345],
       [0.5440072 ],
       [0.64513195],
       [0.59936076],
       [0.74137545],
       [0.8007328 ],
       [0.71230346],
       [0.78412604],
       [0.7102883 ],
       [0.7599248 ],
       [0.9204202 ],
       [0.72694117],
       [0.8562486 ],
       [0.7695912 ],
       [0.6317456 ],
       [0.749

In [111]:
from sklearn.metrics import r2_score

r2_score(y_test, y_pred)

0.727228475965767